### ISSUE TITLE
Add support for dark menu bar (black icon vanishes in menu bar)

### ISSUE THREAD

**Issue by MathiasTim** [timoweiss/tijd#22]
I am using the dark menu bar on mac OS (System Preferences -> General -> Use dark menu bar and Dock) therefore unfortunately the icon of tijd vanishes (i thought the app is not running actually ;) ).

![screen shot 2017-09-28 at 15 57 31](https://user-images.githubusercontent.com/1793379/30970791-5c4ed7fc-a466-11e7-933b-c2957e62ab55.png)

Would be great, if you add a white icon or whatever has to be done to support this. Thank you!

**Comment by michaelknoch** [comment]
see https://github.com/electron/electron/issues/1271 @timoweiss

**Comment by timoweiss** [comment]
thank for reporting @MathiasTim , thanks for the pointer @michaelknoch
